"""Fail-closed diagnostic for the qualified Strands tracer configuration."""

from strands.telemetry.tracer import get_tracer

from .exceptions import TrustGuardConfigurationError


def require_redacted_tracer() -> None:
    """Check actual initialized state, not an environment value changed too late.

    Strands 1.54 has public configuration but no public redaction-state accessor.
    These three read-only diagnostic fields are deliberately version-qualified;
    an absent/changed field refuses strict construction. No tracer is patched and
    no telemetry event or network request is generated by this check.
    """
    tracer = get_tracer()
    if (
        getattr(tracer, "_redaction_enabled", None) is not True
        or getattr(tracer, "_unredacted_exact", None) != frozenset()
        or getattr(tracer, "_unredacted_globs", None) != ()
    ):
        raise TrustGuardConfigurationError(
            "Start a fresh process with OTEL_SEMCONV_STABILITY_OPT_IN="
            "gen_ai_unredacted_attributes= before creating any Strands agent."
        )
